name: cron 

x-cron-base: &cron_base
  image: cron-runner        # the final image name
  build: .
  privileged: true
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - .:/compose
  working_dir: /compose
services:
  cron-app1:
    <<: *cron_base
    privileged: true
    environment:
      CRON_SCHEDULE: "* * * * *"
      # CRON_LOG: "/var/log/cron/cron.log"
      TASK_CMD: "docker compose up --no-deps --force-recreate --attach app1 app1"
  cron-app2:
    <<: *cron_base
    privileged: true
    environment:
      CRON_SCHEDULE: "* * * * *"
      # CRON_LOG: "/var/log/cron/cron.log"
      TASK_CMD: "docker compose up --no-deps --force-recreate --attach app2 app2"
